# Generated by Django 3.0.5 on 2020-04-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appantiga', '0002_registrousuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrousuarios',
            old_name='name',
            new_name='nome',
        ),
    ]
